import { ServiceItem, PillarItem, ProcessStep, Project } from "./types";

export const SERVICES: ServiceItem[] = [
  { title: "Web Applications", description: "Scalable, React-based web application development built for performance and long-term maintainability." },
  { title: "Mobile Apps", description: "High-performance mobile app development with native feel and cross-platform efficiency." },
  { title: "Backend Systems", description: "Robust backend development services with secure APIs, microservices, and scalable architectures." },
  { title: "AI Integration", description: "AI-powered software development including LLM integration, vector databases, and intelligent automation." },
  { title: "MVPs for Startups", description: "MVP development for startups — from idea to market-ready product in weeks, not months." }
];

export const PILLARS: PillarItem[] = [
  {
    title: "Elite Engineers",
    subtitle: "Small teams. Deep thinking. Engineers who understand systems, not just frameworks.",
    icon: "Brain"
  },
  {
    title: "AI-Powered Execution",
    subtitle: "AI-assisted development workflows reduce repetition and accelerate delivery without compromising quality.",
    icon: "Bot"
  },
  {
    title: "Engineering Fundamentals",
    subtitle: "Clean, maintainable code. Scalable systems. Software built to last.",
    icon: "Settings"
  }
];

export const PROCESS_STEPS: ProcessStep[] = [
  {
    number: "01",
    title: "Understand the Problem",
    description: "We don't write a single line of code until we fully understand the business problem and its real-world impact."
  },
  {
    number: "02",
    title: "Design the System",
    description: "Architecture first. Data flows, API contracts, and component hierarchies are mapped before execution."
  },
  {
    number: "03",
    title: "Build with AI Leverage",
    description: "AI tooling accelerates scaffolding so engineers focus on complex logic and product decisions."
  },
  {
    number: "04",
    title: "Test & Refine",
    description: "Automated testing pipelines and rigorous reviews ensure stable, production-ready software."
  },
  {
    number: "05",
    title: "Ship & Support",
    description: "Reliable deployment pipelines, monitoring, and long-term support keep systems healthy at scale."
  }
];

export const PROJECTS: Project[] = [
  {
    slug: "inventory-management",
    name: "Inventory Management",
    client: "Enterprise Client",
    vertical: "Enterprise Software",
    type: "mobile",
    tags: ["client-work", "open-source"],
    role: "Full-stack mobile app & backend",
    summary: "A production-ready, cross-platform inventory system with real-time stock, advanced crash prevention, and role-based access control.",
    problem: "TODO: describe the client problem and the cost of the status quo (multi-location stock chaos, frequent crashes).",
    approach: "Built a comprehensive inventory management system with multi-location support, real-time stock tracking, and hierarchical organization. Implemented advanced crash prevention with multi-layer error handling, automatic recovery, and 23+ error-scenario tests. Features: multi-variant products, barcode scanning, batch & expiry tracking, formula management, role-based access (Master/Employee/User), audit logging, and analytics dashboards. Security via JWT auth, AES-256 encryption, and session monitoring.",
    outcome: "TODO: add measurable outcomes (crash rate, locations supported, time saved).",
    highlights: ["23+ error scenarios hardened", "Role-based access control", "AES-256 encryption + JWT"],
    tech: ["React Native", "Expo", "TypeScript", "Redux Toolkit"],
    cover: "/inventory_management.png",
    gallery: [], // TODO: add real screenshots
    websiteUrl: "",
    githubUrl: "https://github.com/samarthsinh2660/inventory-management-system-frontend",
    status: "live",
  },
  {
    slug: "hillsquills",
    name: "HillsQuills",
    client: "HillsQuills Media",
    vertical: "Media & Publishing",
    type: "web",
    tags: ["client-work", "featured"],
    role: "Full-stack web platform",
    summary: "Uttarakhand's premier news source, bringing the latest stories from the hills.",
    problem: "TODO: describe the publishing/distribution problem this solved.",
    approach: "Built a full editorial platform with a CMS-style admin, authenticated authoring (NextAuth), media handling via Cloudinary, and an SEO-first reader experience.",
    outcome: "TODO: add traffic / readership metrics.",
    highlights: [],
    tech: ["Next.js", "Tailwind CSS", "Node.js", "Express", "MySQL", "NextAuth", "Cloudinary"],
    cover: "/hillsquills.png",
    gallery: [],
    websiteUrl: "https://www.hillsquills.com/",
    githubUrl: "https://github.com/pranavpandey1998official/hills-quills-backend",
    status: "live",
  },
  {
    slug: "uttarakhand-next",
    name: "Uttarakhand Next",
    client: "Uttarakhand Next Media",
    vertical: "Media & Publishing",
    type: "web",
    tags: ["client-work"],
    role: "Full-stack web platform",
    summary: "A modern regional news portal covering the latest from Uttarakhand across politics, culture, and community.",
    problem: "TODO: describe the publishing/distribution problem this solved.",
    approach: "Built a full editorial platform with a CMS-style admin, authenticated authoring (NextAuth), media handling via Cloudinary, and an SEO-first reader experience.",
    outcome: "TODO: add traffic / readership metrics.",
    highlights: [],
    tech: ["Next.js", "Tailwind CSS", "Node.js", "Express", "MySQL", "NextAuth", "Cloudinary"],
    cover: "/uttarakhand_next.png",
    gallery: [],
    websiteUrl: "",
    githubUrl: "",
    status: "live",
  },
  {
    slug: "dr-smit-bharat-solanki",
    name: "Dr. Smit Bharat Solanki Website",
    client: "Dr. Smit Bharat Solanki",
    vertical: "Healthcare",
    type: "web",
    tags: ["client-work", "featured", "brand-site"],
    role: "Full-stack web + SEO",
    summary: "A premium, SEO-optimized medical website delivering women's healthcare information with trust signals and a built-in support chatbot.",
    problem: "TODO: describe the discovery/trust problem for a specialist practice.",
    approach: "Built a production-grade medical site for a gynecologist and robotic surgeon: service pages, an interactive chatbot (Support Circle), research-publications showcase, multi-clinic location pages, WhatsApp appointment integration, FAQ modal, and a gallery. SEO-first architecture with per-page metadata, Open Graph, and sitemap generation; glassmorphism UI.",
    outcome: "TODO: add ranking / appointment-conversion metrics.",
    highlights: ["SEO-first per-page metadata", "WhatsApp appointment booking", "In-page support chatbot"],
    tech: ["Next.js", "Tailwind CSS", "Framer Motion", "TypeScript"],
    cover: "/drwebsite.png",
    gallery: [],
    websiteUrl: "https://www.drsmitbharatsolanki.com/",
    githubUrl: "https://github.com/Prat05devs/DrSolanki",
    status: "live",
  },
  {
    slug: "praeq",
    name: "Praeq Talent Management",
    client: "Praeq Talent Management",
    vertical: "Talent Acquisition",
    type: "web",
    tags: ["client-work", "featured", "brand-site"],
    role: "Design + full-stack web",
    summary: "PRAEQ is a high-performance collective dedicated to transforming exceptional individuals into global icons.",
    problem: "TODO: describe the brand/roster-presentation problem.",
    approach: "Designed and developed a modern, responsive site showcasing the talent roster and services: dynamic multimedia profiles, an intuitive contact system, and SEO + performance optimizations aligned with a premium brand identity.",
    outcome: "TODO: add engagement / inbound metrics.",
    highlights: [],
    tech: ["Next.js", "Tailwind CSS", "TypeScript"],
    cover: "/praeq.png",
    gallery: [],
    websiteUrl: "https://www.praeq.in/",
    githubUrl: "https://github.com/Prat05devs/PRAEQ",
    status: "live",
  },
  {
    slug: "dapper",
    name: "Dapper",
    client: "Sustainable Fashion Initiative",
    vertical: "E-Commerce",
    type: "ecommerce",
    tags: ["in-house", "open-source", "featured"],
    role: "Product + full-stack build",
    summary: "A next-generation sustainable fashion marketplace for buying, selling, and donating pre-owned clothing through a community-driven circular ecosystem.",
    problem: "Thrift/second-hand commerce feels low-trust and low-quality; we set out to make conscious consumption feel premium and desirable.",
    approach: "Built a purpose-driven marketplace with curated listings, seller verification, buy/sell/donate flows, city-based availability discovery, and community trust signals — wrapped in a minimal editorial aesthetic.",
    outcome: `Placed 35th in the Asia-Pacific region and ranked in the top 300 websites globally at Lovable's "No Code Competition" (6,500+ participants).`,
    highlights: ["35th in Asia-Pacific", "Top 300 globally", "6,500+ participants competition"],
    tech: ["Next.js", "Tailwind CSS", "Node.js", "Express", "MongoDB", "NextAuth", "Cloudinary"],
    cover: "/dapper.png",
    gallery: [],
    websiteUrl: "https://dapper-city-threads.lovable.app/",
    githubUrl: "https://github.com/Prat05devs/dapper-city-threads",
    status: "live",
  },
  {
    slug: "payroll-studio",
    name: "Payroll Studio",
    client: "Indian SMBs",
    vertical: "HR & Payroll",
    type: "web",
    tags: ["client-work"],
    role: "Full-stack payroll & HR platform",
    summary: "Complete HR & Payroll built for Indian SMBs — a full-cycle payroll and HR management web app hard-coded for Indian statutory rules with biometric attendance sync and government-format payslips.",
    problem: "Indian SMBs juggle PF, ESIC, PT and TDS compliance across manual spreadsheets and disconnected attendance devices — with high risk of statutory error and delayed payroll cycles.",
    approach: "Shipped a full-cycle payroll and HR web app with Indian statutory rules (PF, ESIC, PT, TDS) auto-calculated, biometric attendance sync from DMPS devices with range processing, a rich admin console and an employee self-service portal in one codebase, and government-format PDF exports (Form 5, ESI, PF, PT summaries). Every payslip matches the government format exactly.",
    outcome: "TODO: add SMB adoption / payroll-cycle metrics.",
    highlights: [
      "PF, ESIC, PT, TDS auto-calculated",
      "Biometric attendance sync with DMPS devices + range processing",
      "Admin console + employee self-service portal in one codebase",
      "Government-format PDF reports: Form 5, ESI, PF, PT summaries",
    ],
    tech: ["Next.js", "TypeScript", "Node.js", "PostgreSQL", "Tailwind CSS"],
    cover: "/payrollStudio.webp",
    gallery: [],
    websiteUrl: "",
    githubUrl: "",
    status: "live",
  },
  {
    slug: "quality-care-clinics",
    name: "Quality Care Clinics — Admin Console",
    client: "Quality Care Clinics, Dubai",
    vertical: "Healthcare — Dental",
    type: "web",
    tags: ["client-work"],
    role: "Admin console for a multi-clinic booking platform",
    summary: "The admin console powering a leading dental group in Dubai — manages doctors, schedules and bookings across multiple clinics, feeding the patient-facing mobile app.",
    problem: "A fast-growing multi-clinic dental group needed a single control plane to run doctors, schedules and appointments across locations — the patient mobile app was creating bookings, but staff had no unified back-office to manage supply, avoid double-booking and coordinate across clinics.",
    approach: "Built a full-featured web admin console that sits behind the patients' mobile booking app: multi-clinic and multi-doctor management, per-doctor schedules and availability windows, appointment lifecycle and slot allocation, and role-based access for clinic staff. Everything the mobile app exposes to patients is controlled here.",
    outcome: "TODO: add booking-volume / clinic-count / staff-adoption metrics.",
    highlights: [
      "Multi-clinic, multi-doctor scheduling",
      "Powers the patient mobile-app booking flow",
      "Doctor rosters + availability windows",
      "Role-based staff access",
    ],
    tech: ["React", "TypeScript", "Node.js", "REST APIs"],
    cover: "/qualitycare_logo.png",
    gallery: [],
    websiteUrl: "",
    githubUrl: "",
    status: "live",
  },
  {
    slug: "campaign-ops",
    name: "CampaignOps",
    client: "In-House",
    vertical: "Event & Campaign Ops",
    type: "ai",
    tags: ["in-house"],
    role: "Product + full-stack build",
    summary: "An AI-assisted event and campaign operations platform that turns a raw idea into a full execution workspace — built for real internal use across government, CSR, community, cafe and outreach campaigns.",
    problem: "Event and campaign teams juggle intake, planning, tasks, vendors, stakeholders, budgets and post-event debriefs across disconnected tools — nothing owns the full lifecycle from idea to execution to reusable playbook.",
    approach: "Building CampaignOps as a purpose-built ops platform: event / campaign intake, type classification, scale and budget planning, AI-generated execution plans, task assignment, vendor and stakeholder management, content calendar, budget tracking, files, activity logs, reports, post-event debriefs, and a reusable playbook / knowledge base — all in one workspace.",
    outcome: "TODO: add internal-usage / event-throughput metrics.",
    highlights: [
      "Idea → execution workspace in one flow",
      "AI-generated execution plans per event type",
      "Vendor, stakeholder and content-calendar management",
      "Reusable playbook / knowledge base from every event",
    ],
    tech: ["Next.js", "TypeScript", "PostgreSQL", "OpenAI"],
    cover: "/campaign-ops.png",
    gallery: [],
    websiteUrl: "",
    githubUrl: "https://github.com/Prat05devs/CampaignOPS",
    status: "live",
  },
  {
    slug: "saffron-hills-studio",
    name: "Saffron Hills Studio",
    client: "Saffron Hills Studio",
    vertical: "Podcast & Recording Studio",
    type: "web",
    tags: ["client-work", "brand-site"],
    role: "Brand site + booking flow",
    summary: "Dehradun's fully-equipped podcast, ad-shoot and broadcast studio — soundproofed rooms, cinema cameras, teleprompter rigs, and a booking flow for creators.",
    problem: "TODO: describe the discovery / booking problem for the studio.",
    approach: "Shipped a polished studio brand site showcasing podcast production, commercial ad shoots and news / media setups, plus the precise gear list (Shure SM7B, Blackmagic, Aperture) and a request-booking flow tuned for creators, agencies and news anchors.",
    outcome: "TODO: add booking / enquiry metrics.",
    highlights: [],
    tech: ["Next.js", "Tailwind CSS", "TypeScript"],
    cover: "/saffronhillsstudio.png",
    gallery: [],
    websiteUrl: "https://www.saffronhillsstudio.com/",
    githubUrl: "",
    status: "live",
  },
  {
    slug: "dormhub",
    name: "DormHub",
    client: "DormHub Dehradun",
    vertical: "Hospitality — Hostels",
    type: "web",
    tags: ["client-work", "brand-site"],
    role: "Brand site + book-a-bunk enquiry flow",
    summary: "Dehradun's backpacker hostel brand — bunk-bed dorms, private retreats and group rooms, community-first, near IT Park on Shashtradhara Road.",
    problem: "TODO: describe the discovery / trust problem for the hostel brand.",
    approach: "Built a friendly, community-forward hostel site with bunk / private / group accommodation showcases, testimonials, and a direct 'book a bunk' enquiry flow with clear location and contact hand-off.",
    outcome: "TODO: add enquiry / occupancy metrics.",
    highlights: [],
    tech: ["Wix", "Custom Design & Content"],
    cover: "/dormhub.png",
    gallery: [],
    websiteUrl: "https://www.dormhub.in/",
    githubUrl: "",
    status: "live",
  },
  {
    slug: "jai-hotel",
    name: "Jai Hotel",
    client: "Jai Hotel, Mandal",
    vertical: "Hospitality — Mountain Stays",
    type: "web",
    tags: ["client-work", "brand-site"],
    role: "Brand site + itinerary planner",
    summary: "A mountain-base hotel in Mandal on the Chopta / Char Dham route — rooms, food, and local itinerary planning for trekkers, families and yatris.",
    problem: "TODO: describe the booking / trip-planning problem for the hotel.",
    approach: "Built a purposeful hotel site tuned to real mountain-travel intent — Mandal Valley rooms, Gopeshwar premium huts and Food Junction — plus an itinerary planner that hands off a WhatsApp-ready plan to the on-ground team.",
    outcome: "TODO: add direct-booking / enquiry metrics.",
    highlights: ["Itinerary planner → WhatsApp hand-off"],
    tech: ["Next.js", "Tailwind CSS", "TypeScript", "Vercel"],
    cover: "/jaihotel.png",
    gallery: [],
    websiteUrl: "https://jai-hotel.vercel.app/",
    githubUrl: "",
    status: "live",
  },
  {
    slug: "holy-sins-cafe",
    name: "Holy Sins Cafes",
    client: "Holy Sins Cafes",
    vertical: "Food & Beverage",
    type: "web",
    tags: ["client-work", "brand-site"],
    role: "Brand site",
    summary: "A moody, cinematic brand experience for Holy Sins Cafes — built around a 360° view and a 'closed circle' invitation to enter the sin.",
    problem: "TODO: describe the discovery / brand problem for the cafe.",
    approach: "Designed a distinctive brand-first cafe site with a cinematic entry, story-led navigation and location hand-off — built to feel as immersive on a phone as inside the cafe.",
    outcome: "TODO: add footfall / social metrics.",
    highlights: [],
    tech: ["Next.js", "Tailwind CSS", "TypeScript"],
    cover: "/holysinscafe.png",
    gallery: [],
    websiteUrl: "https://www.holysincafes.com/",
    githubUrl: "",
    status: "live",
  },
  {
    slug: "axocom",
    name: "AxoCom",
    client: "Axolotl Emprise LLP",
    vertical: "Media & Communications",
    type: "web",
    tags: ["client-work", "brand-site"],
    role: "Corporate website",
    summary: "Corporate site for AxoCom — a tech-first media company powering a portfolio of news and content brands with its proprietary AI Core.",
    problem: "TODO: describe the positioning problem for a tech-first media house.",
    approach: "Designed and shipped a bold, editorial corporate site that positions AxoCom as an engineered media house — mapping its services (strategy, PR, campaigns, AI-generated content), the AI Core pipeline (inputs → pipelines → knowledge graph → AI engines → outputs), and the wider media universe of eight publications.",
    outcome: "TODO: add inbound / brand metrics.",
    highlights: ["Showcases the AI Core pipeline", "Media universe of 8 publications"],
    tech: ["Next.js", "Tailwind CSS", "TypeScript"],
    cover: "/axocom.png",
    gallery: [],
    websiteUrl: "https://www.axocom.in/",
    githubUrl: "",
    status: "live",
  },
  {
    slug: "kumbh-milan",
    name: "Kumbh Milan",
    client: "UrbanMatch Inc.",
    vertical: "Social Networking",
    type: "mobile",
    tags: ["client-work", "open-source"],
    role: "Mobile app + realtime backend",
    summary: "A hyper-local social discovery platform enabling millions of pilgrims to connect during the Kumbh Mela.",
    problem: "Pilgrims at the world's largest religious gathering had no reliable way to discover and reach people nearby under extreme network and load conditions.",
    approach: "Built a scalable mobile app with real-time geolocation, chat, and community discovery, backed by infrastructure tuned for peak concurrent traffic across variable network conditions.",
    outcome: "Handled millions of concurrent users during one of the world's largest religious gatherings.",
    highlights: ["Millions of concurrent users", "Real-time geolocation + chat"],
    tech: ["Flutter", "Firebase", "Real-Time Geolocation"],
    cover: "/kumbhmilap.png",
    gallery: [],
    websiteUrl: "",
    githubUrl: "https://github.com/basictech01/kumbh-milan",
    status: "live",
  },
  {
    slug: "doonplot",
    name: "DoonPlot",
    client: "Real Estate Agencies",
    vertical: "PropTech",
    type: "web",
    tags: ["client-work", "open-source"],
    role: "Geospatial web app",
    summary: "Modernizing land sales by replacing static brochures with interactive, mobile-first geospatial experiences.",
    problem: "Agents sold land with static brochures that failed to convey boundaries, location, and context, hurting engagement and conversion.",
    approach: "Built a property mapping platform integrating Google Maps with custom GeoJSON for interactive visualization, boundary mapping, and location-based search — mobile-first so agents can present on-the-go.",
    outcome: "TODO: add engagement / conversion metrics.",
    highlights: ["Interactive GeoJSON boundary mapping"],
    tech: ["React", "Google Maps API", "GeoJSON"],
    cover: "/doonplot.png",
    gallery: [],
    websiteUrl: "https://doonplot.in",
    githubUrl: "https://github.com/basictech01/LandMarketing",
    status: "live",
  },
  {
    slug: "cricketvotecrypto",
    name: "CricketVoteCrypto",
    client: "CricketVote",
    vertical: "Web3 & Gaming",
    type: "web3",
    tags: ["in-house", "open-source"],
    role: "Smart contracts + dApp frontend",
    summary: "A decentralized IPL prediction platform using smart contracts and cryptographic verification for trustless rewards.",
    problem: "Prediction games rely on a trusted operator to hold funds and settle outcomes — a single point of failure and mistrust.",
    approach: "Built a blockchain prediction platform on Ethereum smart contracts: users predict, stake tokens, and receive automated rewards based on match outcomes, with cryptographic verification for trustless, transparent settlement. Web3.js for chain interactions; React frontend.",
    outcome: "TODO: add usage metrics.",
    highlights: ["Trustless on-chain settlement"],
    tech: ["Solidity", "Web3.js", "React"],
    cover: "/cricketProphet.png",
    gallery: [],
    websiteUrl: "",
    githubUrl: "https://github.com/basictech01/cricketvoteblockchain",
    status: "live",
  },
  {
    slug: "ha-group",
    name: "HA Group",
    client: "HA Group",
    vertical: "Business Setup & Consulting",
    type: "web",
    tags: ["client-work", "featured", "brand-site"],
    year: "2024",
    role: "Full-stack web + SEO",
    summary: "A Dubai-based business setup consultancy website helping entrepreneurs launch and scale companies across the UAE.",
    problem: "Entrepreneurs setting up in Dubai were getting stuck in paperwork, waiting weeks for approvals, and losing time to unreliable advice — with no single trusted place to understand costs, jurisdictions, and next steps.",
    approach: "Designed and built a conversion-focused corporate site for HA Group covering business setup, value-added services (Power of Attorney, HR consultancy, banking), and multi-emirate expansion. Included an interactive setup-cost calculator, expert-consultation CTAs, a Refer & Earn program, service and jurisdiction pages, and an SEO-first content architecture with per-page metadata to rank on high-intent queries like \"business setup in Dubai & UAE\".",
    outcome: "Helped freelancers become founders, families turn investments into companies, and startups scale across multiple emirates over 5+ years of operation.",
    highlights: [
      "5+ years helping entrepreneurs set up in the UAE",
      "Interactive business setup cost calculator",
      "Mainland + free-zone jurisdiction coverage",
      "Value-added services: PoA, HR, banking",
    ],
    tech: ["Next.js", "Tailwind CSS", "TypeScript"],
    cover: "/ha-group.png",
    gallery: [],
    websiteUrl: "",
    githubUrl: "",
    status: "live",
  },
];
