import { ServiceItem, PillarItem, ProcessStep, Project } from "./types";

export const SERVICES: ServiceItem[] = [
  { title: "Web Applications", description: "Scalable, React-based web application development built for performance and long-term maintainability." },
  { title: "Mobile Apps", description: "High-performance mobile app development with native feel and cross-platform efficiency." },
  { title: "Backend Systems", description: "Robust backend development services with secure APIs, microservices, and scalable architectures." },
  { title: "AI Integration", description: "AI-powered software development including LLM integration, vector databases, and intelligent automation." },
  { title: "MVPs for Startups", description: "MVP development for startups — from idea to market-ready product in weeks, not months." }
];

export const PILLARS: PillarItem[] = [
  {
    title: "Elite Engineers",
    subtitle: "Small teams. Deep thinking. Engineers who understand systems, not just frameworks.",
    icon: "Brain"
  },
  {
    title: "AI-Powered Execution",
    subtitle: "AI-assisted development workflows reduce repetition and accelerate delivery without compromising quality.",
    icon: "Bot"
  },
  {
    title: "Engineering Fundamentals",
    subtitle: "Clean, maintainable code. Scalable systems. Software built to last.",
    icon: "Settings"
  }
];

export const PROCESS_STEPS: ProcessStep[] = [
  {
    number: "01",
    title: "Understand the Problem",
    description: "We don't write a single line of code until we fully understand the business problem and its real-world impact."
  },
  {
    number: "02",
    title: "Design the System",
    description: "Architecture first. Data flows, API contracts, and component hierarchies are mapped before execution."
  },
  {
    number: "03",
    title: "Build with AI Leverage",
    description: "AI tooling accelerates scaffolding so engineers focus on complex logic and product decisions."
  },
  {
    number: "04",
    title: "Test & Refine",
    description: "Automated testing pipelines and rigorous reviews ensure stable, production-ready software."
  },
  {
    number: "05",
    title: "Ship & Support",
    description: "Reliable deployment pipelines, monitoring, and long-term support keep systems healthy at scale."
  }
];

export const PROJECTS: Project[] = [
  {
    slug: "inventory-management",
    name: "Inventory Management",
    client: "Enterprise Client",
    vertical: "Enterprise Software",
    type: "mobile",
    tags: ["client-work", "open-source"],
    role: "Full-stack mobile app & backend",
    summary: "A production-ready, cross-platform inventory system with real-time stock, advanced crash prevention, and role-based access control.",
    caseStudy: {
      overview: "A production-ready, cross-platform inventory system with real-time stock, advanced crash prevention, and role-based access control.",
      challenge: "TODO: describe the client problem and the cost of the status quo (multi-location stock chaos, frequent crashes).",
      keyConstraints: [
        "Support multi-location stock without losing data integrity.",
        "Keep mobile workflows stable across unreliable device and network conditions.",
        "Protect inventory, staff, and audit data behind clear access boundaries.",
      ],
      approach: "Built a comprehensive inventory management system with multi-location support, real-time stock tracking, and hierarchical organization. Implemented advanced crash prevention with multi-layer error handling, automatic recovery, and 23+ error-scenario tests. Features: multi-variant products, barcode scanning, batch & expiry tracking, formula management, role-based access (Master/Employee/User), audit logging, and analytics dashboards. Security via JWT auth, AES-256 encryption, and session monitoring.",
      outcome: "TODO: add measurable outcomes (crash rate, locations supported, time saved).",
      whatMadeThisWork: ["23+ error scenarios hardened", "Role-based access control", "AES-256 encryption + JWT"],
    },
    tech: ["React Native", "Expo", "TypeScript", "Redux Toolkit"],
    cover: "/inventory_management.png",
    gallery: [], // TODO: add real screenshots
    websiteUrl: "",
    githubUrl: "https://github.com/samarthsinh2660/inventory-management-system-frontend",
    status: "live",
  },
  {
    slug: "hillsquills",
    name: "HillsQuills",
    client: "HillsQuills Media",
    vertical: "Media & Publishing",
    type: "web",
    tags: ["client-work", "featured"],
    role: "Full-stack web platform",
    summary: "Uttarakhand's premier news source, bringing the latest stories from the hills.",
    caseStudy: {
      overview: "Uttarakhand's premier news source, bringing the latest stories from the hills.",
      challenge: "TODO: describe the publishing/distribution problem this solved.",
      keyConstraints: [
        "Give editors a reliable publishing workflow.",
        "Handle media-heavy stories without slowing the reader experience.",
        "Structure content for search discovery and social sharing.",
      ],
      approach: "Built a full editorial platform with a CMS-style admin, authenticated authoring (NextAuth), media handling via Cloudinary, and an SEO-first reader experience.",
      outcome: "TODO: add traffic / readership metrics.",
      whatMadeThisWork: [],
    },
    tech: ["Next.js", "Tailwind CSS", "Node.js", "Express", "MySQL", "NextAuth", "Cloudinary"],
    cover: "/hillsquills.png",
    gallery: [],
    websiteUrl: "https://www.hillsquills.com/",
    githubUrl: "https://github.com/pranavpandey1998official/hills-quills-backend",
    status: "live",
  },
  {
    slug: "uttarakhand-next",
    name: "Uttarakhand Next",
    client: "Uttarakhand Next Media",
    vertical: "Media & Publishing",
    type: "web",
    tags: ["client-work"],
    role: "Full-stack web platform",
    summary: "A modern regional news portal covering the latest from Uttarakhand across politics, culture, and community.",
    caseStudy: {
      overview: "A modern regional news portal covering the latest from Uttarakhand across politics, culture, and community.",
      challenge: "TODO: describe the publishing/distribution problem this solved.",
      keyConstraints: [
        "Support frequent regional publishing across categories.",
        "Keep article pages fast, searchable, and easy to share.",
        "Give the team simple controls for authors, media, and story updates.",
      ],
      approach: "Built a full editorial platform with a CMS-style admin, authenticated authoring (NextAuth), media handling via Cloudinary, and an SEO-first reader experience.",
      outcome: "TODO: add traffic / readership metrics.",
      whatMadeThisWork: [],
    },
    tech: ["Next.js", "Tailwind CSS", "Node.js", "Express", "MySQL", "NextAuth", "Cloudinary"],
    cover: "/uttarakhand_next.png",
    gallery: [],
    websiteUrl: "",
    githubUrl: "",
    status: "live",
  },
  {
    slug: "dr-smit-bharat-solanki",
    name: "Dr. Smit Bharat Solanki Website",
    client: "Dr. Smit Bharat Solanki",
    vertical: "Healthcare",
    type: "web",
    tags: ["client-work", "featured", "brand-site"],
    role: "Full-stack web + SEO",
    summary: "A premium, SEO-optimized medical website delivering women's healthcare information with trust signals and a built-in support chatbot.",
    caseStudy: {
      overview: "A premium, SEO-optimized medical website delivering women's healthcare information with trust signals and a built-in support chatbot.",
      challenge: "TODO: describe the discovery/trust problem for a specialist practice.",
      keyConstraints: [
        "Present medical information with clarity and trust.",
        "Make appointment intent easy to convert from mobile.",
        "Support search visibility across services, publications, and clinic locations.",
      ],
      approach: "Built a production-grade medical site for a gynecologist and robotic surgeon: service pages, an interactive chatbot (Support Circle), research-publications showcase, multi-clinic location pages, WhatsApp appointment integration, FAQ modal, and a gallery. SEO-first architecture with per-page metadata, Open Graph, and sitemap generation; glassmorphism UI.",
      outcome: "TODO: add ranking / appointment-conversion metrics.",
      whatMadeThisWork: ["SEO-first per-page metadata", "WhatsApp appointment booking", "In-page support chatbot"],
    },
    tech: ["Next.js", "Tailwind CSS", "Framer Motion", "TypeScript"],
    cover: "/drwebsite.png",
    gallery: [],
    websiteUrl: "https://www.drsmitbharatsolanki.com/",
    githubUrl: "https://github.com/Prat05devs/DrSolanki",
    status: "live",
  },
  {
    slug: "praeq",
    name: "Praeq Talent Management",
    caseStudyTitle: "Digital Platform for a Talent Acquisition and Management Brand",
    client: "Praeq Talent Management",
    vertical: "Talent Acquisition",
    type: "web",
    tags: ["client-work", "featured", "brand-site"],
    role: "Web developer",
    summary: "A business website for Praeq Talent Management designed to communicate hiring services, brand credibility, and talent acquisition expertise.",
    caseStudy: {
      overview: "Praeq Talent Management operates in the talent acquisition space, helping businesses and professionals connect through structured hiring and recruitment services.",
      challenge: "The brand needed a clear digital presence that could explain its talent acquisition services, build trust, and present the company professionally to clients and candidates.",
      challengeItems: [
        "Communicate recruitment and talent services clearly.",
        "Build credibility for business clients and candidates.",
        "Create a clean service-led website experience.",
        "Make the brand look professional and trustworthy.",
      ],
      keyConstraints: [
        "The website had to be business-focused and easy to understand.",
        "The content needed to speak to both clients and talent.",
        "The design had to feel professional, not template-like.",
      ],
      approach: "Created a structured business website around service clarity, trust-building, and talent acquisition positioning.",
      approachItems: [
        {
          title: "Brand Positioning",
          description: "Presented Praeq as a professional talent management and hiring partner.",
        },
        {
          title: "Service Communication",
          description: "Structured the content around recruitment, hiring support, and talent solutions.",
        },
        {
          title: "Trust-Oriented Web Experience",
          description: "Designed the website to feel credible for business visitors and candidates.",
        },
      ],
      outcome: "Praeq received a professional digital presence that explains its talent acquisition work and supports brand credibility.",
      outcomeItems: [
        "Created a clear web identity for the talent brand.",
        "Improved service presentation.",
        "Built a stronger first impression for clients and candidates.",
      ],
      whatMadeThisWork: [
        "Talent acquisition website.",
        "Professional brand positioning.",
        "Service-led content structure.",
        "Business-focused web design.",
      ],
    },
    tech: ["Next.js", "Tailwind CSS", "TypeScript"],
    cover: "/praeq.png",
    gallery: [],
    websiteUrl: "https://www.praeq.in/",
    githubUrl: "https://github.com/Prat05devs/PRAEQ",
    status: "live",
  },
  {
    slug: "dapper",
    name: "Dapper",
    caseStudyTitle: "Reimagining Thrift Fashion as a Community-Led Circular Fashion Platform",
    client: "Dapper",
    vertical: "Fashion / Sustainability / Circular Commerce",
    type: "web",
    tags: ["client-work", "featured"],
    role: "Full-stack developer",
    summary: "A premium thrift fashion platform built to help Gen Z users list, discover, donate, and celebrate pre-loved fashion through a community-first digital experience.",
    caseStudy: {
      overview: "Dapper is a premium thrift and circular fashion platform created around the idea that pre-loved clothing should not feel like a compromise. The platform positions second-hand fashion as stylish, sustainable, community-driven, and culturally relevant for the next generation of conscious consumers.",
      challenge: "Traditional thrift stores are often seen as unorganized, low-trust, or purely transactional. Dapper needed to present thrift as something bigger: a curated, trusted, stylish, and community-led movement around circular fashion.",
      keyConstraints: [
        "Make pre-loved fashion feel premium and aspirational.",
        "Build trust around authenticity, quality, and seller participation.",
        "Communicate circular fashion in a way Gen Z users can emotionally connect with.",
        "Create a platform identity that feels like a movement, not just a store.",
        "Support both discovery and contribution through listings or donations.",
        "Balance style, sustainability, and community storytelling.",
        "Explain the founder's vision, mission, values, and donation purpose clearly.",
        "Use a scalable backend foundation with Supabase.",
        "Support future marketplace workflows such as listings, sellers, donations, and curated products.",
      ],
      approach: "Built Dapper as a brand-led circular fashion platform, combining storytelling, sustainability messaging, community positioning, and a scalable web foundation.",
      approachItems: [
        {
          title: "Founder-Led Brand Story",
          description: "Created a strong founder message that frames Dapper as a community movement around pre-loved fashion, not just a thrift store.",
        },
        {
          title: "Circular Fashion Positioning",
          description: "Structured the platform around sustainability, conscious consumption, and extending the life of quality garments.",
        },
        {
          title: "Community-First Marketplace Direction",
          description: "Positioned users as both buyers and contributors, encouraging them to list rare pieces, designer clothing, limited-edition sneakers, watches, bags, and other pre-loved items.",
        },
        {
          title: "Donation Experience",
          description: "Added a purpose-driven donation section explaining how users can give clothing back to local communities or support responsible recycling.",
        },
        {
          title: "Trust and Values Framework",
          description: "Highlighted values like quality curation, authenticity, community trust, sustainable impact, conscious consumption, and seller empowerment.",
        },
        {
          title: "Supabase Backend Foundation",
          description: "Used Supabase as the backend layer for managing platform data and supporting future workflows around products, sellers, listings, donations, or user-generated content.",
        },
      ],
      outcome: "Dapper became a live digital platform with a clear identity around premium thrift, circular fashion, sustainability, and community-led discovery.",
      outcomeItems: [
        "Created a strong brand narrative for a premium thrift platform.",
        "Positioned second-hand fashion as stylish, sustainable, and aspirational.",
        "Built a scalable web foundation using Next.js and Supabase.",
        "Communicated donation, recycling, seller empowerment, and conscious consumption clearly.",
        "Turned the platform from a simple fashion website into a movement-led brand experience.",
      ],
      whatMadeThisWork: [
        {
          title: "Movement-Led Positioning",
          description: "Dapper was not written or designed like a normal thrift store. The platform was framed as a circular fashion movement built around community, identity, and sustainability.",
        },
        {
          title: "Premium Thrift Narrative",
          description: "The brand language made pre-loved clothing feel curated, desirable, and culturally relevant for modern fashion consumers.",
        },
        {
          title: "Sustainability With Style",
          description: "The experience connected conscious consumption with personal style, helping users see sustainability as aspirational instead of limiting.",
        },
        {
          title: "Scalable Product Foundation",
          description: "Next.js and Supabase provided a modern foundation for future marketplace features, seller workflows, listings, donations, and content management.",
        },
      ],
    },
    tech: ["Next.js", "React", "TypeScript", "Supabase"],
    cover: "/dapper.png",
    gallery: [],
    websiteUrl: "https://dapper-city-threads.lovable.app/about",
    githubUrl: "",
    status: "live",
  },
  {
    slug: "payroll-studio",
    name: "Payroll Studio",
    client: "Indian SMBs",
    vertical: "HR & Payroll",
    type: "web",
    tags: ["client-work"],
    role: "Full-stack payroll & HR platform",
    summary: "Complete HR & Payroll built for Indian SMBs — a full-cycle payroll and HR management web app hard-coded for Indian statutory rules with biometric attendance sync and government-format payslips.",
    caseStudy: {
      overview: "Complete HR & Payroll built for Indian SMBs — a full-cycle payroll and HR management web app hard-coded for Indian statutory rules with biometric attendance sync and government-format payslips.",
      challenge: "Indian SMBs juggle PF, ESIC, PT and TDS compliance across manual spreadsheets and disconnected attendance devices — with high risk of statutory error and delayed payroll cycles.",
      keyConstraints: [
        "Encode Indian statutory payroll rules accurately.",
        "Synchronize biometric attendance data without manual cleanup.",
        "Produce government-format documents that teams can use directly.",
      ],
      approach: "Shipped a full-cycle payroll and HR web app with Indian statutory rules (PF, ESIC, PT, TDS) auto-calculated, biometric attendance sync from DMPS devices with range processing, a rich admin console and an employee self-service portal in one codebase, and government-format PDF exports (Form 5, ESI, PF, PT summaries). Every payslip matches the government format exactly.",
      outcome: "TODO: add SMB adoption / payroll-cycle metrics.",
      whatMadeThisWork: [
        "PF, ESIC, PT, TDS auto-calculated",
        "Biometric attendance sync with DMPS devices + range processing",
        "Admin console + employee self-service portal in one codebase",
        "Government-format PDF reports: Form 5, ESI, PF, PT summaries",
      ],
    },
    tech: ["Next.js", "TypeScript", "Node.js", "PostgreSQL", "Tailwind CSS"],
    cover: "/payrollStudio.webp",
    gallery: [],
    websiteUrl: "",
    githubUrl: "",
    status: "live",
  },
  {
    slug: "quality-care-clinics",
    name: "Quality Care Clinics — Admin Console",
    caseStudyTitle: "Admin Console for Managing Doctors, Appointments, and Multi-Clinic Scheduling",
    client: "Quality Care Clinics, Dubai",
    vertical: "Healthcare — Dental",
    type: "web",
    tags: ["client-work"],
    role: "Full-stack / frontend developer",
    summary: "A web-based admin console built for a Dubai dental clinic to manage doctor schedules, clinic assignments, and patient appointments across multiple clinic locations.",
    caseStudy: {
      overview: "Quality Care Clinics is a Dubai-based dental clinic group with multiple doctors and clinic locations. The client wanted to build on top of their mobile application so patients could book appointments while the internal team could manage doctors, schedules, and appointment operations from a centralized admin panel.",
      challenge: "The client needed a reliable back-office system to support their mobile appointment booking application. Their team had to manage doctor availability, clinic-wise scheduling, and appointments across different dental clinic locations without operational confusion.",
      challengeItems: [
        "Manage a team of doctors across multiple dental clinic locations.",
        "Schedule doctors between different clinics based on availability.",
        "Support appointment management for the patient-facing mobile app.",
        "Create an admin panel that could sit on top of the existing application flow.",
        "Give clinic staff a centralized system instead of scattered manual coordination.",
      ],
      keyConstraints: [
        "The admin panel had to connect with the mobile app's appointment flow.",
        "Doctor scheduling needed to work across multiple clinic locations.",
        "Clinic staff needed a simple interface for daily use.",
        "The system had to manage appointments without creating scheduling conflicts.",
        "The solution had to extend the existing application instead of replacing the whole system.",
      ],
      approach: "Built a web-based admin console that acted as the operational control panel behind the mobile appointment booking experience.",
      approachItems: [
        {
          title: "Doctor Management",
          description: "Created workflows to manage doctor profiles, rosters, and availability.",
        },
        {
          title: "Clinic Scheduling",
          description: "Enabled staff to assign doctors to different dental clinic locations based on schedule and availability.",
        },
        {
          title: "Appointment Management",
          description: "Supported appointment visibility and management for bookings coming through the mobile application.",
        },
        {
          title: "Admin Control Panel",
          description: "Built a centralized web interface where staff could manage the operational side of the mobile app.",
        },
        {
          title: "Existing App Extension",
          description: "Designed the admin panel as an added operational layer on top of the client's existing application ecosystem.",
        },
      ],
      outcome: "The clinic received a centralized admin panel that helped their team manage doctors, appointments, and clinic-wise schedules from one place.",
      outcomeItems: [
        "Created a back-office system for the mobile booking application.",
        "Improved visibility into doctor schedules and clinic assignments.",
        "Made appointment management easier for clinic staff.",
        "Reduced dependency on manual coordination between clinics.",
        "Provided a scalable base for future appointment and clinic operations.",
        {
          title: "Appointment Flow",
          description: "Mobile app + admin panel.",
        },
        {
          title: "Project Status",
          description: "Live.",
        },
      ],
      whatMadeThisWork: [
        {
          title: "Operational Layer Behind the Mobile App",
          description: "The admin panel was built to support the real clinic operations behind the patient-facing appointment booking experience.",
        },
        {
          title: "Multi-Clinic Scheduling Logic",
          description: "The system focused on assigning doctors across different clinic locations, which was central to the client's workflow.",
        },
        {
          title: "Staff-Friendly Admin Experience",
          description: "The interface was designed for clinic staff who needed to manage daily appointments and schedules quickly.",
        },
        {
          title: "Built Around Existing Workflows",
          description: "The solution extended the existing application setup instead of forcing the client to rebuild everything from scratch.",
        },
      ],
    },
    tech: ["React", "TypeScript", "Node.js", "REST APIs"],
    cover: "/qualitycare_logo.png",
    gallery: [],
    websiteUrl: "",
    githubUrl: "",
    status: "live",
  },
  {
    slug: "campaign-ops",
    name: "CampaignOps",
    client: "In-House",
    vertical: "Event & Campaign Ops",
    type: "ai",
    tags: ["in-house"],
    role: "Product + full-stack build",
    summary: "CampaignOps is an AI-assisted event and campaign operations system built for teams that plan, execute, track, and learn from real-world events.",
    caseStudy: {
      overview: [
        "CampaignOps is an AI-assisted event and campaign operations system built for teams that plan, execute, track, and learn from real-world events.",
        "The product was designed around a simple but serious problem: event execution is rarely handled in one place. Teams usually depend on WhatsApp chats, spreadsheets, scattered files, calls, memory, and last-minute coordination. CampaignOps brings all of that into one structured command centre where teams can manage events, tasks, vendors, contacts, budgets, outreach, files, reports, activity logs, and AI-assisted planning.",
        "The long-term vision is to turn every completed event into reusable operational intelligence, so the next event becomes smarter.",
      ],
      challenge: [
        "Event and campaign execution becomes complex very quickly.",
        "A single event can involve venue planning, vendor coordination, budget estimation, stakeholder communication, government or client approvals, invite lists, content planning, file sharing, team responsibilities, reporting, and post-event learning.",
        "Most teams lose important knowledge after every event. Vendor feedback, budget mistakes, delayed tasks, outreach messages, permission issues, and operational risks often stay inside people's heads or scattered across chats.",
        "CampaignOps was created to solve this gap by converting event chaos into structured operational memory.",
      ],
      keyConstraints: [
        "The product had to support different event types, from small meetups to large government or CSR events.",
        "Each event required multiple workflows: tasks, vendors, budget, contacts, content, outreach, files, and reports.",
        "AI could not behave like a generic chatbot. It needed to generate structured, reviewable outputs.",
        "The system needed role-based access for admins, managers, and members.",
        "The architecture had to keep the database as the source of truth, with AI acting only as an assistive planning layer.",
        "The MVP had to stay honest: AI proposes, humans approve, and approved outputs can later become real app records.",
      ],
      approach: [
        "We designed CampaignOps as an event command centre instead of a simple dashboard.",
        "Each event gets its own workspace with dedicated sections for overview, tasks, timeline, budget, vendors, contacts, outreach, content, files, AI plan, activity log, and reports.",
        "The system uses event taxonomy to understand context before planning. A 40-person founder meetup and a 2,000-person government summit do not need the same budget, vendors, approvals, tasks, or risk planning. CampaignOps classifies events using type, subtype, scale, budget, timeline, stakeholders, and brand context.",
        "The AI layer was designed as an operations planner. It can generate event flows, manpower plans, vendor requirements, logistics checklists, risk plans, media plans, and post-event report structures. But the AI output remains reviewable and editable before being accepted by the team.",
        "On the engineering side, CampaignOps is built as a full-stack TypeScript product using Next.js, NestJS, Prisma, PostgreSQL, JWT authentication, role-based access control, activity logs, and structured API workflows.",
      ],
      outcome: [
        "CampaignOps creates a structured way for teams to move from raw event requirements to execution-ready workspaces.",
        "It helps teams:",
      ],
      outcomeItems: [
        "Organize event planning in one place",
        "Assign and track responsibilities clearly",
        "Maintain vendor and stakeholder records",
        "Track estimated vs actual budgets",
        "Store event files, proposals, templates, and reports",
        "Generate AI-assisted plans without losing human control",
        "Preserve post-event learning for future use",
        "Build reusable operational memory over time",
      ],
      outcomeClosing: "The biggest outcome is not just better planning. It is the ability to make every completed event improve the next one.",
      whatMadeThisWork: [],
      whatMadeThisWorkBody: [
        "The strength of CampaignOps is its grounding in real event operations.",
        "It is not positioned as a generic AI wrapper, CRM, or task manager. The system understands that event work involves people, budgets, vendors, approvals, timelines, documents, reporting, and last-minute changes.",
        "The product's long-term moat is accumulated execution intelligence: vendor history, budget patterns, outreach templates, task timelines, risk checklists, post-event debriefs, and reusable playbooks.",
        "That makes CampaignOps more than a planning tool. It becomes the operating memory of an event-driven organization.",
      ],
    },
    tech: ["Next.js", "TypeScript", "PostgreSQL", "OpenAI"],
    cover: "/campaign-ops.png",
    gallery: [],
    websiteUrl: "",
    githubUrl: "https://github.com/Prat05devs/CampaignOPS",
    status: "live",
  },
  {
    slug: "saffron-hills-studio",
    name: "Saffron Hills Studio",
    caseStudyTitle: "Web Presence for a Podcast and Recording Studio",
    client: "Saffron Hills Studio",
    vertical: "Podcast & Recording Studio",
    type: "web",
    tags: ["client-work", "brand-site"],
    role: "Web developer",
    summary: "A studio website designed to present Saffron Hills Studio as a professional space for podcasting, recording, and creative media production.",
    caseStudy: {
      overview: "Saffron Hills Studio is a podcast and recording studio brand built around creative production, audio recording, and media-focused services.",
      challenge: "The studio needed a website that could show its creative identity, explain its services, and make the space feel professional and approachable for creators.",
      challengeItems: [
        "Present podcast and recording services clearly.",
        "Create a premium creative-studio feel.",
        "Help visitors understand what the studio offers.",
        "Support inquiries or bookings through a simple digital flow.",
      ],
      keyConstraints: [
        "The website had to feel creative but still professional.",
        "The service offering needed to be easy to understand.",
        "The design had to support a media/studio brand identity.",
      ],
      approach: "Built a brand-led website that explains the studio offering and gives the space a polished digital identity.",
      approachItems: [
        {
          title: "Studio Positioning",
          description: "Presented the studio as a dedicated space for podcasting and recording.",
        },
        {
          title: "Service Presentation",
          description: "Structured key services around recording, podcast production, and creative media work.",
        },
        {
          title: "Inquiry Direction",
          description: "Prepared the website to guide visitors toward booking or contacting the studio.",
        },
      ],
      outcome: "Saffron Hills Studio received a focused web presence that supports discovery, credibility, and service communication.",
      outcomeItems: [
        "Created a clear identity for the studio online.",
        "Presented services in a structured way.",
        "Improved the brand's discoverability and professionalism.",
      ],
      whatMadeThisWork: [
        "Podcast studio website.",
        "Recording studio positioning.",
        "Creative service presentation.",
        "Inquiry-focused structure.",
      ],
    },
    tech: ["Next.js", "Tailwind CSS", "TypeScript"],
    cover: "/saffronhillsstudio.png",
    gallery: [],
    websiteUrl: "https://www.saffronhillsstudio.com/",
    githubUrl: "",
    status: "live",
  },
  {
    slug: "dormhub",
    name: "DormHub",
    client: "DormHub Dehradun",
    vertical: "Hospitality — Hostels",
    type: "web",
    tags: ["client-work", "brand-site"],
    role: "Brand site + book-a-bunk enquiry flow",
    summary: "Dehradun's backpacker hostel brand — bunk-bed dorms, private retreats and group rooms, community-first, near IT Park on Shashtradhara Road.",
    caseStudy: {
      overview: "Dehradun's backpacker hostel brand — bunk-bed dorms, private retreats and group rooms, community-first, near IT Park on Shashtradhara Road.",
      challenge: "TODO: describe the discovery / trust problem for the hostel brand.",
      keyConstraints: [
        "Make accommodations, location, and community feel immediately clear.",
        "Build trust for travelers comparing stays on mobile.",
        "Keep the enquiry hand-off direct and low-friction.",
      ],
      approach: "Built a friendly, community-forward hostel site with bunk / private / group accommodation showcases, testimonials, and a direct 'book a bunk' enquiry flow with clear location and contact hand-off.",
      outcome: "TODO: add enquiry / occupancy metrics.",
      whatMadeThisWork: [],
    },
    tech: ["Wix", "Custom Design & Content"],
    cover: "/dormhub.png",
    gallery: [],
    websiteUrl: "https://www.dormhub.in/",
    githubUrl: "",
    status: "live",
  },
  {
    slug: "jai-hotel",
    name: "Jai Hotel",
    caseStudyTitle: "Hospitality Website for a Mountain Stay Experience",
    client: "Jai Hotel",
    vertical: "Hospitality - Mountain Stays",
    type: "web",
    tags: ["client-work", "brand-site"],
    role: "Web developer",
    summary: "A hospitality website for Jai Hotel designed to showcase a mountain stay experience and help visitors understand the property before booking.",
    caseStudy: {
      overview: "Jai Hotel is a hospitality brand focused on mountain stays, serving guests looking for a comfortable travel and lodging experience.",
      challenge: "The hotel needed a clean digital presence that could communicate the stay experience, show the property, and make the brand more credible for potential guests.",
      challengeItems: [
        "Showcase the hotel and mountain stay experience.",
        "Present rooms, amenities, and location clearly.",
        "Build trust for guests before they inquire or book.",
        "Create a responsive website for travel users browsing on mobile.",
      ],
      keyConstraints: [
        "The website had to visually support a hospitality brand.",
        "Information needed to be simple for travelers to scan.",
        "The design had to work well on mobile.",
      ],
      approach: "Created a guest-focused hospitality website around property presentation, location context, and simple inquiry flow.",
      approachItems: [
        {
          title: "Property Presentation",
          description: "Structured the website to highlight the hotel, stay experience, and guest-facing details.",
        },
        {
          title: "Hospitality Content",
          description: "Presented rooms, amenities, and location information in a clear way.",
        },
        {
          title: "Responsive Experience",
          description: "Built the website to work smoothly for guests browsing from mobile or desktop.",
        },
      ],
      outcome: "Jai Hotel received a dedicated online presence that supports discovery, trust-building, and guest inquiries.",
      outcomeItems: [
        "Created a professional web presence for the hotel.",
        "Improved presentation of the mountain stay experience.",
        "Made hotel information easier for guests to access.",
      ],
      whatMadeThisWork: [
        "Hotel website.",
        "Mountain stay positioning.",
        "Guest-focused content.",
        "Responsive hospitality design.",
      ],
    },
    tech: ["Next.js", "Tailwind CSS", "TypeScript", "Vercel"],
    cover: "/jaihotel.png",
    gallery: [],
    websiteUrl: "https://jai-hotel.vercel.app/",
    githubUrl: "",
    status: "live",
  },
  {
    slug: "holy-sins-cafe",
    name: "Holy Sins Cafes",
    caseStudyTitle: "Digital Brand Presence for a Food and Beverage Cafe",
    client: "Holy Sins Cafes",
    vertical: "Food & Beverage",
    type: "web",
    tags: ["client-work", "brand-site"],
    role: "Web developer",
    summary: "A food and beverage website for Holy Sins Cafes designed to present the cafe brand, menu experience, and customer-facing identity online.",
    caseStudy: {
      overview: "Holy Sins Cafes is a food and beverage brand built around cafe culture, customer experience, and lifestyle-led dining.",
      challenge: "The cafe needed a digital presence that could communicate its brand personality, present offerings clearly, and make the business feel discoverable and memorable online.",
      challengeItems: [
        "Present the cafe brand in a visually appealing way.",
        "Show food, beverage, and cafe experience clearly.",
        "Support customer discovery through a web presence.",
        "Create a brand feel beyond a basic menu page.",
      ],
      keyConstraints: [
        "The website had to feel warm, visual, and food-oriented.",
        "The content needed to be easy for customers to explore.",
        "The brand presentation had to support both discovery and recall.",
      ],
      approach: "Built a brand-focused cafe website that combines food presentation, brand storytelling, and customer-friendly navigation.",
      approachItems: [
        {
          title: "Cafe Brand Experience",
          description: "Created a web identity that reflects the cafe's food and lifestyle positioning.",
        },
        {
          title: "Menu / Offering Presentation",
          description: "Structured the website to make food and beverage offerings easy to discover.",
        },
        {
          title: "Customer-Facing Web Presence",
          description: "Designed the experience for visitors exploring the cafe before visiting or contacting.",
        },
      ],
      outcome: "Holy Sins Cafes received a polished web presence that supports brand discovery and customer engagement.",
      outcomeItems: [
        "Created a digital identity for the cafe.",
        "Improved online presentation of the food and beverage brand.",
        "Made the cafe easier to discover and understand online.",
      ],
      whatMadeThisWork: [
        "Cafe brand website.",
        "Food and beverage presentation.",
        "Customer-focused layout.",
        "Responsive design.",
      ],
    },
    tech: ["Next.js", "Tailwind CSS", "TypeScript"],
    cover: "/holysinscafe.png",
    gallery: [],
    websiteUrl: "https://www.holysincafes.com/",
    githubUrl: "",
    status: "live",
  },
  {
    slug: "axocom",
    name: "AxoCom",
    caseStudyTitle: "Corporate Website for a Media and Communications Company",
    client: "AxoCom",
    vertical: "Media & Communications",
    type: "web",
    tags: ["client-work", "brand-site"],
    role: "Web developer / product and content collaborator",
    summary: "A corporate website for AxoCom designed to present the company's media, communications, events, and digital initiatives in one professional web presence.",
    caseStudy: {
      overview: "AxoCom is a media and communications company working across events, digital media, public relations, and related ventures. The website needed to communicate the company's identity and make its work visible to clients, partners, and stakeholders.",
      challenge: "The company needed a unified digital presence that could bring together its media properties, event work, services, and communication initiatives under one clear brand identity.",
      challengeItems: [
        "Present multiple company activities in one website.",
        "Communicate media, communications, and event capabilities.",
        "Build credibility for clients and institutional stakeholders.",
        "Showcase company ventures without making the site feel scattered.",
      ],
      keyConstraints: [
        "The website had to represent multiple business directions.",
        "The content needed to be clear for clients, partners, and stakeholders.",
        "The design had to feel professional and credible.",
        "The structure had to support future updates around events and ventures.",
      ],
      approach: "Created a corporate website that organizes AxoCom's identity, services, ventures, and event-related work into a structured digital presence.",
      approachItems: [
        {
          title: "Company Positioning",
          description: "Presented AxoCom as a media and communications company with multiple active initiatives.",
        },
        {
          title: "Services and Ventures",
          description: "Structured the website to explain services, properties, and related business activities.",
        },
        {
          title: "Event and Media Visibility",
          description: "Supported presentation of events, media work, and company updates.",
        },
        {
          title: "Stakeholder Credibility",
          description: "Designed the site to feel reliable for clients, partners, and public-facing communication.",
        },
      ],
      outcome: "AxoCom received a unified corporate website that helps present its services, ventures, media work, and communication identity more professionally.",
      outcomeItems: [
        "Created a single digital home for the company.",
        "Improved visibility of services and ventures.",
        "Supported credibility for client and stakeholder conversations.",
        "Made the company's media and event work easier to present.",
      ],
      whatMadeThisWork: [
        "Corporate website.",
        "Media and communications positioning.",
        "Company ventures presentation.",
        "Event and stakeholder-facing content.",
        "Professional brand presence.",
      ],
    },
    tech: ["Next.js", "Tailwind CSS", "TypeScript"],
    cover: "/axocom.png",
    gallery: [],
    websiteUrl: "https://www.axocom.in/",
    githubUrl: "",
    status: "live",
  },
  {
    slug: "kumbh-milan",
    name: "Kumbh Milan",
    client: "UrbanMatch Inc.",
    vertical: "Social Networking",
    type: "mobile",
    tags: ["client-work", "open-source"],
    role: "Mobile app + realtime backend",
    summary: "A hyper-local social discovery platform enabling millions of pilgrims to connect during the Kumbh Mela.",
    caseStudy: {
      overview: "A hyper-local social discovery platform enabling millions of pilgrims to connect during the Kumbh Mela.",
      challenge: "Pilgrims at the world's largest religious gathering had no reliable way to discover and reach people nearby under extreme network and load conditions.",
      keyConstraints: [
        "Keep discovery and chat responsive under extreme crowd density.",
        "Handle variable network quality during a live mass gathering.",
        "Protect location-based interactions while keeping the UX simple.",
      ],
      approach: "Built a scalable mobile app with real-time geolocation, chat, and community discovery, backed by infrastructure tuned for peak concurrent traffic across variable network conditions.",
      outcome: "Handled millions of concurrent users during one of the world's largest religious gatherings.",
      whatMadeThisWork: ["Millions of concurrent users", "Real-time geolocation + chat"],
    },
    tech: ["Flutter", "Firebase", "Real-Time Geolocation"],
    cover: "/kumbhmilap.png",
    gallery: [],
    websiteUrl: "",
    githubUrl: "https://github.com/basictech01/kumbh-milan",
    status: "live",
  },
  {
    slug: "doonplot",
    name: "DoonPlot",
    client: "Real Estate Agencies",
    vertical: "PropTech",
    type: "web",
    tags: ["client-work", "open-source"],
    role: "Geospatial web app",
    summary: "Modernizing land sales by replacing static brochures with interactive, mobile-first geospatial experiences.",
    caseStudy: {
      overview: "Modernizing land sales by replacing static brochures with interactive, mobile-first geospatial experiences.",
      challenge: "Agents sold land with static brochures that failed to convey boundaries, location, and context, hurting engagement and conversion.",
      keyConstraints: [
        "Represent land boundaries accurately and clearly.",
        "Make map interactions usable during field sales conversations.",
        "Keep location context visible on mobile devices.",
      ],
      approach: "Built a property mapping platform integrating Google Maps with custom GeoJSON for interactive visualization, boundary mapping, and location-based search — mobile-first so agents can present on-the-go.",
      outcome: "TODO: add engagement / conversion metrics.",
      whatMadeThisWork: ["Interactive GeoJSON boundary mapping"],
    },
    tech: ["React", "Google Maps API", "GeoJSON"],
    cover: "/doonplot.png",
    gallery: [],
    websiteUrl: "https://doonplot.in",
    githubUrl: "https://github.com/basictech01/LandMarketing",
    status: "live",
  },
  {
    slug: "cricketvotecrypto",
    name: "CricketVoteCrypto",
    client: "CricketVote",
    vertical: "Web3 & Gaming",
    type: "web3",
    tags: ["in-house", "open-source"],
    role: "Smart contracts + dApp frontend",
    summary: "A decentralized IPL prediction platform using smart contracts and cryptographic verification for trustless rewards.",
    caseStudy: {
      overview: "A decentralized IPL prediction platform using smart contracts and cryptographic verification for trustless rewards.",
      challenge: "Prediction games rely on a trusted operator to hold funds and settle outcomes — a single point of failure and mistrust.",
      keyConstraints: [
        "Move settlement logic on-chain without making the interface intimidating.",
        "Keep prediction, staking, and reward flows transparent.",
        "Verify outcomes in a way users can trust.",
      ],
      approach: "Built a blockchain prediction platform on Ethereum smart contracts: users predict, stake tokens, and receive automated rewards based on match outcomes, with cryptographic verification for trustless, transparent settlement. Web3.js for chain interactions; React frontend.",
      outcome: "TODO: add usage metrics.",
      whatMadeThisWork: ["Trustless on-chain settlement"],
    },
    tech: ["Solidity", "Web3.js", "React"],
    cover: "/cricketProphet.png",
    gallery: [],
    websiteUrl: "",
    githubUrl: "https://github.com/basictech01/cricketvoteblockchain",
    status: "live",
  },
  {
    slug: "ha-group",
    name: "HA Group",
    client: "HA Group",
    vertical: "Business Setup & Consulting",
    type: "web",
    tags: ["client-work", "featured", "brand-site"],
    year: "2024",
    role: "Full-stack web + SEO",
    summary: "A Dubai-based business setup consultancy website helping entrepreneurs launch and scale companies across the UAE.",
    caseStudy: {
      overview: "A Dubai-based business setup consultancy website helping entrepreneurs launch and scale companies across the UAE.",
      challenge: "Entrepreneurs setting up in Dubai were getting stuck in paperwork, waiting weeks for approvals, and losing time to unreliable advice — with no single trusted place to understand costs, jurisdictions, and next steps.",
      keyConstraints: [
        "Make complex jurisdiction and service options easier to compare.",
        "Capture high-intent consultation leads without slowing research.",
        "Build SEO depth around competitive UAE business setup queries.",
      ],
      approach: "Designed and built a conversion-focused corporate site for HA Group covering business setup, value-added services (Power of Attorney, HR consultancy, banking), and multi-emirate expansion. Included an interactive setup-cost calculator, expert-consultation CTAs, a Refer & Earn program, service and jurisdiction pages, and an SEO-first content architecture with per-page metadata to rank on high-intent queries like \"business setup in Dubai & UAE\".",
      outcome: "Helped freelancers become founders, families turn investments into companies, and startups scale across multiple emirates over 5+ years of operation.",
      whatMadeThisWork: [
        "5+ years helping entrepreneurs set up in the UAE",
        "Interactive business setup cost calculator",
        "Mainland + free-zone jurisdiction coverage",
        "Value-added services: PoA, HR, banking",
      ],
    },
    tech: ["Next.js", "Tailwind CSS", "TypeScript"],
    cover: "/ha-group.png",
    gallery: [],
    websiteUrl: "",
    githubUrl: "",
    status: "live",
  },
];
